name: EnumRTP
main: com.enumdev.enumrtp.Main
version: 1.0
api-version: 1.16
author: Liebert
description: Плагин для управления телепортациями. Плагин создан студией EnumDev
commands:
  rtp:
    description: Открыть меню RTP
    usage: /rtp
  rtpreload:
    description: Перезагрузить конфигурацию EnumRTP
    usage: /rtpreload
    permission: enumrtp.reload
permissions:
  enumrtp.reload:
    description: Разрешает перезагрузку конфигурации EnumRTP
    default: op
